Don't use the -Wshadow CXX FLAG
It causes the following error (Qt version 4.8.1 i386-linux-gnu):
/usr/include/qt4/QtCore/qtconcurrentrunbase.h:84:42: error: declaration
of ‘future’ shadows a member of 'this' [-Werror=shadow]

Change-Id: I55fe238155948fbd1289f3c5f02596ac0167c0f5
Signed-off-by: Luís Pereira <luis.artur.pereira@gmail.com>
Reviewed-by: David Faure (KDE) <faure@kde.org>